- name: install and run nginx
  hosts: web
  become: yes #it will give root access
  tasks:
    - name: install ngnix packages
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
        name: nginx
        state: started
        enabled: yes     