# file level variable
- name: variables from play level
  hosts: localhost
  vars:
  - variables.yaml
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: hi , i am learning {{Course}} , from {{month}} to {{comple}}}