# prompt level variables
- name: variables from play level
  hosts: localhost
  vars_prompt:
  - name: username
    prompt:  enter the username
    private: false  # user can see what they are entering
  - name: password
    prompt:  enter the password
    private: true # user can't see what they are entering
    
  tasks: 
  - name: print and check variables
    ansible.builtin.debug:
      msg: username is {{username}} , password is {{password}}